# Generated by Django 5.1.7 on 2025-05-07 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='sensores',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='sensores',
            name='valor',
        ),
        migrations.AddField(
            model_name='historico',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historico',
            name='valor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ambientes',
            name='sig',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='status',
            field=models.BooleanField(),
        ),
    ]
